In [1]:
import tensorflow as tf

In [2]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


In [3]:
mnist = tf.keras.datasets.mnist

In [5]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test, = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 32s 3us/step


In [6]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

c:\Users\Saeed\miniconda3\envs\tensorflow\lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.10354942,  0.25931638,  0.95220053, -0.09258542,  0.44494382,
        -0.2569451 ,  0.4460273 , -0.30210823, -0.20349954,  0.46491793]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.07075187, 0.10170177, 0.20335004, 0.07153185, 0.12244624,
        0.06069025, 0.12257897, 0.05801027, 0.06402212, 0.12491658]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

2.8019722

In [11]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8627 - loss: 0.4704
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9542 - loss: 0.1508
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9678 - loss: 0.1067
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9730 - loss: 0.0880
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9775 - loss: 0.0736


In [13]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9772 - loss: 0.0762


[0.07620299607515335, 0.9771999716758728]

In [14]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.86205042e-08, 1.38232599e-08, 1.01157120e-05, 1.63605800e-04,
        4.28342388e-12, 4.77955427e-06, 7.65505552e-13, 9.99819934e-01,
        8.62019306e-07, 6.93177412e-07],
       [1.68011880e-07, 8.40843495e-05, 9.99904275e-01, 1.09550883e-05,
        2.25288085e-15, 3.84429370e-07, 5.12718490e-09, 1.01168802e-13,
        2.01927257e-08, 1.85471986e-13],
       [8.15436181e-07, 9.96622086e-01, 8.20568879e-04, 3.33223797e-05,
        9.20247749e-06, 1.39267092e-06, 4.39566102e-05, 2.31269957e-03,
        1.54600115e-04, 1.34785068e-06],
       [9.99756753e-01, 1.21851675e-08, 1.50729014e-04, 1.20299660e-07,
        3.35539198e-07, 5.55517090e-06, 8.07878387e-05, 2.99129579e-06,
        1.34655110e-07, 2.56577982e-06],
       [1.21940930e-05, 4.18891988e-09, 4.82393370e-05, 4.23233821e-08,
        9.98309731e-01, 1.68822021e-06, 1.04616611e-05, 2.13897816e-04,
        2.47148910e-05, 1.37902971e-03]], dtype=float32)>